### ISSUE TITLE
Dependencies: Adding more types

### ISSUE THREAD

**Issue by ilarsf** [statgen/SLURM-examples#6]
Found the following dependency helpful, too:
`sbatch --dependency=afterany:`
(job can begin after the specified jobs have terminated)

Excellent but probably too detailed guide for our SLURM-examples here: 
Building pipelines using slurm dependencies: https://hpc.nih.gov/docs/job_dependencies.html

**Comment by pjvandehaar** [comment]
Should we just add a link at the bottom of the section <https://github.com/statgen/SLURM-examples/blob/master/README.md#job-dependencies>?

**Comment by dtaliun** [comment]
i would add links only to the official slurm documentation. 3rd party tutorials may assume specific slurm version/configuration.
